In [40]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline
import random

# parameters
gridSize = 4
states_terminal = [[0,0], [gridSize-1, gridSize-1]]
valid_actions = [[-1, 0], [1, 0], [0, 1], [0, -1]]
gamma = 0.1 # discount rate
currentReward = -1
numIterations = 100
alpha = 0.001 #exploration factor

# initialization
Q = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]

Populating the interactive namespace from numpy and matplotlib


In [41]:
def generateInitialState():
    #generate a random initial state
    return states[np.random.randint(len(states))]

def generateNextAction():
    #generate a random action from the valid set of actions
    return valid_actions[np.random.randint(len(valid_actions))]

# define the transition function from a given state and action
def getNextState(state, action):
    
    #define what happens when reaching a terminal state
    if is_terminal_state(state):
        reward = 0
        return reward, state

    # here you should complete this step, the transition step
    nextState = np.add(state, action)

    # if the agent reaches a wall
    if -1 in nextState or gridSize in nextState:
        nextState = state
    
    return currentReward, nextState

def is_terminal_state(currentState):
    for state in states_terminal:
        if state[0] == currentState[0] and state[1] == currentState[1]:
            return True
    return False

In [42]:
for it in range(numIterations):
    currentState = generateInitialState()
    
    while True:
        currentAction = generateNextAction()
        reward, nextState = getNextState(currentState, currentAction)
        
        #complete the stop action if the agent reached the goal state
        if reward == 0:
            break
        
        #update the Q-value function Q       
        a = (1 - alpha) * Q[currentState[0]][currentState[1]] 
        b = alpha * (reward + gamma * Q[nextState[0]][nextState[1]])
        Q[currentState[0]][currentState[1]] = a + b
        
        #assign as current state the next state
        currentState = nextState
        
print(Q)

[[ 0.         -0.05744775 -0.07349213 -0.09835541]
 [-0.09381986 -0.08091744 -0.08002192 -0.08371272]
 [-0.13410764 -0.0966115  -0.0864671  -0.05937658]
 [-0.13938613 -0.10568079 -0.07902128  0.        ]]
